run: build
	adl FoveaChatApp-app.xml

build:
	amxmlc -source-path=../src -source-path=libs/shapes/src -library-path=libs/starling.swc -library-path=libs/feathers.swc FoveaChatApp.as

clean:
	rm -f FoveaChatApp.swf
